#!/usr/bin/env bash
set -euo pipefail
if [[ $# -ne 2 ]]; then
  echo "usage: run_selected.sh ABS_BUILD_DIR ABS_LOG_DIR" >&2
  exit 2
fi
BUILD_DIR="$1"
LOG_DIR="$2"
mkdir -p "$LOG_DIR"
set +u  # ROS setup scripts may reference unset trace variables.
source /opt/ros/jazzy/setup.bash
SCRATCH_DIR="$(dirname "$BUILD_DIR")"
source "$SCRATCH_DIR/install/setup.bash"
set -u
export ROS_LOCALHOST_ONLY=1
export ROS_DOMAIN_ID=218
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
run_test() {
  local name="$1" binary="$2" filter="$3"
  if [[ -n "$filter" ]]; then
    "$BUILD_DIR/$binary" --gtest_filter="$filter" 2>&1 | tee "$LOG_DIR/$name.log"
  else
    "$BUILD_DIR/$binary" 2>&1 | tee "$LOG_DIR/$name.log"
  fi
}
run_test episode navigation_runtime/test_execution_episode 'ExecutionEpisode.HotRetargetKeepsActiveBackupUntilSuccessorCommits:ExecutionEpisode.LateRetainedRoleFromAStaleCandidateCannotRewriteSuccessor:ExecutionEpisode.SuspendAndClearDoNotRetainCommandIdentity:ExecutionEpisode.CommitUpdatesLifecycleAndRecoveryInOneSnapshot:ExecutionEpisode.FailClosedClearsCommandExposure'
run_test runtime_fsm navigation_runtime/test_planner_fsm 'PlannerFsm.ResumesOnlyExactFreshWorldRecertifiedGeneration:PlannerFsm.StoppedRecoveryFailureRemainsRetryableWithoutCommand:PlannerFsm.FiveSecondTimeoutExistsOnlyWhileStationary:PlannerFsm.WatchdogKeepsBoundedStoppedRecoveryHoldForRetry:PlannerFsm.PendingGoalOwnerLinearizesSupersedeAndExactConsumption:PlannerFsm.BackupOutsideAcceptanceSchedulesMeasuredRestart:PlannerFsm.RetainsPendingStatusWhileSafetySuffixDrains:PlannerFsm.PreservesObservedTerminalHoldAcrossRestRetry'
run_test continuation navigation_runtime/test_certified_continuation 'CertifiedContinuation.*'
run_test mission_adapter px4_navigation_external_mode/test_navigation_mode_progression ''
run_test mission_semantics px4_navigation_external_mode/test_mission 'MissionController.PassThroughRequiresPerUpdateMainContinuationWitness:MissionController.PassThroughAcceptsRecentMeasuredSegmentCrossingAtCruiseSpeed:MissionController.PassThroughRejectsCrossingAcrossStaleMeasuredGap:MissionController.CoincidentPassThroughStopRestoresTerminalReadiness:MissionController.TerminalStopRequiresMeasuredPositionInsideAcceptanceRadius:MissionController.TerminalStopRequiresLowMeasuredSpeed:MissionController.NativeReadinessCannotClearPendingTerminalStopHold:MissionController.CertifiedPassThroughSuffixStopAllowsMeasuredProgression:MissionController.SafetyTrajectoryCannotAdvancePassThroughUntilCertifiedStop'
run_test command_contract px4_navigation_external_mode/test_navigation_command 'NavigationCommandContract.*'
run_test governor navigation_planning_backend/test_planner_config 'PlannerSpeedGovernor.*:PlannerBackupBraking.AbortIsObservedBetweenBoundedDurationTrials:PlannerBackupBraking.AbortIsObservedInsideTerminalAltitudeAdjustment'
run_test runtime_terminal navigation_runtime/test_navigation_runtime_terminal_monitor 'NavigationRuntimeTerminalMonitorStrict.AdmissionAtOriginalMainEndPreservesItsEpisode:NavigationRuntimeTerminalMonitorStrict.AdmissionRejectsWrongEpochFrameAndReceiveStaleness:NavigationRuntimeTerminalMonitorStrict.ImmediatePreparedEpochResetCannotCommit:NavigationRuntimeTerminalMonitorStrict.ImmediatePreparedFailureCannotCommit:NavigationRuntimeTerminalMonitorStrict.ImmediatePreparedGoalChangeCannotCommit:NavigationRuntimeTerminalMonitorStrict.EmergencyEpisodeCutoverPrecedesAckAndWorldCopy:NavigationRuntimeTerminalMonitor.ExactNativeStartPreservesFreshMainOnlyOwner:NavigationRuntimeTerminalMonitorStrict.ExactNativeStartPreservesFreshMainOnlyOwner:NavigationRuntimeTerminalMonitor.PendingAndGoalTransitionDoNotOpenTerminalMonitor'
run_test timeline_store navigation_execution/test_committed_bundle_store 'ExecutionTimelineStore.WorldAdvanceInvalidatesPendingSuccessor:ExecutionTimelineStore.RecertifiedPredecessorKeepsSuccessorActivationValid:CommittedBundleStore.RecertifiesOnlyTheValidatedBundleOnWorldAdvance:CommittedBundleStore.RecertificationMismatchOrGoalChangeClearsBundle:CommittedBundleStore.ExposureMustRecheckFreshnessAfterWaitingForStoreLock'
run_test world_store navigation_runtime/test_world_snapshot_store 'WorldSnapshotStore.AuthorizationRejectsStaleIdentityWithoutInvokingCommit:WorldSnapshotStore.PublicationCannotInterleaveAnAuthorizedCommit:WorldSnapshotStore.PublishAndFinalizeKeepsDependentStateOrdered:WorldSnapshotStore.WorldAdvanceAfterCandidateValidationCannotCommitCommand:WorldSnapshotStore.AllowsStaleCertificateWhenChangeProvenanceIsDisjoint'
run_test runtime_handover navigation_runtime/test_navigation_runtime_shutdown 'NavigationRuntimeHandover.DispatchesNewStopAfterCompletedTerminalCommand'
run_test facade_candidate navigation_planning_backend/test_planner_facade 'PlannerFacade.CoincidentPassToStopPreservesCertifiedTerminalBackup'
