#!/usr/bin/env python3
"""PX4-native External Mode acceptance scenario.

The default scenario publishes a bounded goal to the product-owned planning
boundary and observes the trajectory generated by ``navigation_runtime`` at
the PX4 TrajectorySetpoint boundary. A deterministic stationary fixture is
still available for isolated adapter tests. The scenario selects
the registered external mode from VehicleStatus, arms, enters the mode, then
hands control back to PX4 POSCTL. It never lands or disarms the vehicle, and it
does not publish OffboardControlMode or use the Offboard mode path.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import signal
import time
from typing import Any

from planner_trace import normalize_planner_trace_record


def _time_ns(value: Any) -> int:
    return int(value.sec) * 1_000_000_000 + int(value.nanosec)


def _finite_vector(values: Any, size: int = 3) -> bool:
    try:
        return len(values) == size and all(math.isfinite(float(value)) for value in values)
    except (TypeError, ValueError):
        return False


def _json_vector(values: Any) -> list[float | None]:
    """Keep intentional PX4 NaN sentinel values JSON-serializable."""
    result: list[float | None] = []
    for value in values:
        number = float(value)
        result.append(number if math.isfinite(number) else None)
    return result


def _percentile(values: list[float], fraction: float) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    index = min(len(ordered) - 1, round((len(ordered) - 1) * fraction))
    return ordered[index]


_MODE_STATUS_NAMES = {
    0: "ACTIVE",
    1: "BRAKING",
    2: "PAUSED",
    3: "COMPLETE",
    4: "FAILED",
}
_MODE_STATUS_REASON_NAMES = {
    0: "NONE",
    1: "SAFETY_STOP",
    2: "OPERATOR_TAKEOVER",
    3: "ODOMETRY_STALE",
    4: "TRAJECTORY_INVALID",
}


class ExternalModeScenario:
    def __init__(self, output: Path, config: dict[str, Any]) -> None:
        import rclpy
        from geometry_msgs.msg import Point, Vector3
        from nav_msgs.msg import Odometry
        from navigation_interfaces.msg import NavigationGoal, NavigationModeStatus, PlannedTrajectory
        try:
            from navigation_interfaces.msg import PlannerCycleTrace
        except ImportError:  # Compatibility with an install before the v2 contract.
            PlannerCycleTrace = None
        from px4_msgs.msg import (
            ModeCompleted,
            TrajectorySetpoint,
            VehicleCommand,
            VehicleCommandAck,
            VehicleLandDetected,
            VehicleLocalPosition,
            VehicleStatus,
        )
        from std_msgs.msg import Bool
        from sensor_msgs.msg import PointCloud2
        from rclpy.node import Node
        from rclpy.qos import QoSProfile, ReliabilityPolicy
        from rosgraph_msgs.msg import Clock

        self.rclpy = rclpy
        self.Node = Node
        self.NavigationGoal = NavigationGoal
        self.NavigationModeStatus = NavigationModeStatus
        self.Point = Point
        self.Vector3 = Vector3
        self.VehicleCommand = VehicleCommand
        self.ModeCompleted = ModeCompleted
        self.VehicleStatus = VehicleStatus
        self.Bool = Bool
        self.VehicleLandDetected = VehicleLandDetected
        self.output = output
        self.output.parent.mkdir(parents=True, exist_ok=True)
        self.stream = output.with_suffix(".jsonl").open("w", encoding="utf-8")
        self.config = config.get("scenario", config)
        self.interactive_handover = bool(self.config.get("interactive_handover", False))
        self.manual_takeoff = bool(self.config.get("manual_takeoff", False))
        self.execution = str(self.config.get("execution", "single_goal"))
        if self.execution not in {"single_goal", "mission"}:
            raise ValueError(f"unsupported scenario execution: {self.execution}")
        self.wall_start = time.monotonic()
        self.sim_start_ns: int | None = None
        self.sim_now_ns = 0
        self.latest_odom: dict[str, float] | None = None
        self.latest_odom_stamp_ns: int | None = None
        self.latest_ground_truth: dict[str, float] | None = None
        self.latest_ground_truth_stamp_ns: int | None = None
        self.goal_publish_count = 0
        self.goal_received_count = 0
        self.goal_request_id = 0
        self.latest_goal: dict[str, Any] = {}
        self.goal_indices: list[int] = []
        self.latest_status: dict[str, Any] = {}
        self.latest_local_position: dict[str, Any] = {}
        self.previous_nav_state: int | None = None
        self.external_mode_id: int | None = None
        self.mode_entered = False
        self.mode_active = False
        self.mode_entered_sim_ns: int | None = None
        self.mode_exit_observed = False
        self.mode_completion_result: int | None = None
        self.mode_failure_observed = False
        self.mission_unexpected_exit_observed = False
        self.mission_complete_observed = False
        self.exit_requested = False
        self.exit_request_sim_ns: int | None = None
        self.takeoff_requested = False
        self.takeoff_requested_sim_ns: int | None = None
        self.takeoff_observed = False
        self.takeoff_stable_since_ns: int | None = None
        self.arm_ack_success_sim_ns: int | None = None
        self.post_takeoff_mode_entered = False
        self.pre_activation_ready_since_ns: int | None = None
        self.navigation_activation_started_sim_ns: int | None = None
        self.land_requested = False
        self.land_requested_sim_ns: int | None = None
        self.land_trigger: str | None = None
        self.land_trigger_detail: dict[str, Any] = {}
        self.grounded_observed = False
        self.landed_detector_current = False
        self.terminal_outcome: str | None = None
        self.handover_waiting = False
        self.operator_aborted = False
        self.mode_status_state: int | None = None
        self.mode_status_reason: int | None = None
        self.waypoint_acceptance_events: list[dict[str, Any]] = []
        self.trajectory_received = 0
        self.trajectory_success_count = 0
        self.latest_trajectory: dict[str, Any] = {}
        self.trajectory_records: list[dict[str, Any]] = []
        # Keep every successful rolling-horizon bundle.  trajectory_records is
        # intentionally retained as the compact, latest-per-waypoint view used
        # by the legacy acceptance checks; the history is the authoritative
        # artifact for splice/continuity analysis.
        self.trajectory_history: list[dict[str, Any]] = []
        self.planner_trace_records: list[dict[str, Any]] = []
        self.trajectory_role_counts: dict[str, int] = {}
        self.safety_kind_counts: dict[str, int] = {}
        self.trajectory_failure_count = 0
        self.safety_transition_count = 0
        self.fallback_latencies_ms: list[float] = []
        self.pending_nominal_failure_ns: int | None = None
        self.actual_min_clearance_m: float | None = None
        self.minimum_collision_clearance_m: float | None = None
        self.minimum_collision_obstacle_name: str | None = None
        self.collision_count = 0
        self.collision_event_count = 0
        self._in_collision = False
        self.setpoint_speed_samples: list[float] = []
        self.measured_speed_samples: list[float] = []
        self._trajectory_record_indices: dict[tuple[str, int], int] = {}
        self.setpoint_count = 0
        self.finite_setpoint_count = 0
        self.ack_count = 0
        self.command_acks: list[dict[str, Any]] = []
        self.events: list[dict[str, Any]] = []
        self.last_command_ns: dict[str, int] = {}
        self.last_trajectory_ns = -10**18
        self.last_goal_ns = -10**18
        self.armed_seen = False
        self.failsafe_seen = False
        self.unexpected_rtl = False
        self.finished = False
        self.failure = ""
        self.lio_gt_origin_offset: tuple[float, float, float] | None = None
        self.localization_divergence_started_ns: int | None = None
        self.localization_divergence_failure = False
        self.first_divergence_event: dict[str, Any] | None = None
        self.max_lio_position_residual_m = 0.0
        self.lio_position_residual_samples: list[float] = []
        self.max_lio_velocity_residual_m_s = 0.0
        self.max_lio_velocity_residual_m_s = 0.0
        self.raw_lidar_scan_count = 0
        self.raw_lidar_roi_scan_count = 0
        self.raw_lidar_roi_max_points = 0
        self.occupied_scan_count = 0
        self.occupied_roi_max_points = 0

        self.node = Node("uav_navigation_external_mode_scenario")
        px4_qos = QoSProfile(depth=20, reliability=ReliabilityPolicy.BEST_EFFORT)
        reliable_qos = QoSProfile(depth=10, reliability=ReliabilityPolicy.RELIABLE)
        self.trajectory_pub = self.node.create_publisher(PlannedTrajectory, "/navigation/trajectory", reliable_qos)
        self.goal_pub = self.node.create_publisher(NavigationGoal, "/navigation/goal", reliable_qos)
        self.command_pub = self.node.create_publisher(VehicleCommand, "/fmu/in/vehicle_command", px4_qos)
        self.node.create_subscription(Clock, "/clock", self._clock, px4_qos)
        self.node.create_subscription(Odometry, "/lio/odometry_propagated", self._odometry, reliable_qos)
        self.node.create_subscription(Odometry, "/sim/ground_truth/odometry", self._ground_truth, reliable_qos)
        self.node.create_subscription(PointCloud2, "/lidar/points", self._raw_lidar, px4_qos)
        self.node.create_subscription(PointCloud2, "/navigation_mapping/visualization/occupied", self._occupied_map, px4_qos)
        self.node.create_subscription(VehicleLocalPosition, "/fmu/out/vehicle_local_position_v1", self._local_position, px4_qos)
        self.node.create_subscription(VehicleStatus, "/fmu/out/vehicle_status_v1", self._status, px4_qos)
        # ModeCompleted has MESSAGE_VERSION=0, so PX4 publishes it without a
        # version suffix (unlike VehicleStatus and VehicleLocalPosition).
        self.node.create_subscription(ModeCompleted, "/fmu/out/mode_completed", self._mode_completed, px4_qos)
        self.node.create_subscription(VehicleLandDetected, "/fmu/out/vehicle_land_detected", self._land_detected, px4_qos)
        self.node.create_subscription(TrajectorySetpoint, "/fmu/in/trajectory_setpoint", self._setpoint, px4_qos)
        self.node.create_subscription(NavigationGoal, "/navigation/goal", self._goal, reliable_qos)
        self.node.create_subscription(PlannedTrajectory, "/navigation/trajectory", self._trajectory, reliable_qos)
        if PlannerCycleTrace is not None:
            self.node.create_subscription(
                PlannerCycleTrace,
                "/navigation/planner_trace",
                self._planner_trace,
                reliable_qos,
            )
        self.node.create_subscription(Bool, "/navigation/mission_complete", self._mission_complete, reliable_qos)
        self.node.create_subscription(
            NavigationModeStatus, "/navigation/mode_status", self._mode_status, reliable_qos)
        self.node.create_subscription(VehicleCommandAck, "/fmu/out/vehicle_command_ack", self._ack, px4_qos)
        self.timer = self.node.create_timer(0.05, self._tick)

    def _record(self, kind: str, payload: dict[str, Any]) -> None:
        self.stream.write(json.dumps({
            "kind": kind,
            "sim_time_ns": self.sim_now_ns,
            "payload": payload,
        }, sort_keys=True, allow_nan=False) + "\n")

    def _clock(self, message: Any) -> None:
        self.sim_now_ns = _time_ns(message.clock)
        if self.sim_now_ns > 0 and self.sim_start_ns is None:
            self.sim_start_ns = self.sim_now_ns

    def _odometry(self, message: Any) -> None:
        if message.header.frame_id != "lio_odom":
            return
        position = message.pose.pose.position
        values = (float(position.x), float(position.y), float(position.z))
        if all(math.isfinite(value) for value in values):
            velocity = tuple(float(value) for value in (
                message.twist.twist.linear.x,
                message.twist.twist.linear.y,
                message.twist.twist.linear.z,
            ))
            if not all(math.isfinite(value) for value in velocity):
                velocity = (0.0, 0.0, 0.0)
            self.latest_odom = {
                "x": values[0], "y": values[1], "z": values[2],
                "vx": velocity[0], "vy": velocity[1], "vz": velocity[2],
            }
            self.latest_odom_stamp_ns = _time_ns(message.header.stamp)
            self._update_localization_watchdog()

    def _ground_truth(self, message: Any) -> None:
        position = message.pose.pose.position
        values = (float(position.x), float(position.y), float(position.z))
        if not all(math.isfinite(value) for value in values):
            return
        velocity = tuple(float(value) for value in (
            message.twist.twist.linear.x,
            message.twist.twist.linear.y,
            message.twist.twist.linear.z,
        ))
        if not all(math.isfinite(value) for value in velocity):
            velocity = (0.0, 0.0, 0.0)
        self.latest_ground_truth = {
            "x": values[0], "y": values[1], "z": values[2],
            "vx": velocity[0], "vy": velocity[1], "vz": velocity[2],
        }
        self.latest_ground_truth_stamp_ns = _time_ns(message.header.stamp)
        self._update_localization_watchdog()
        vehicle_radius = float(self.config.get("vehicle_collision_radius_m", 0.35))
        if not math.isfinite(vehicle_radius) or vehicle_radius <= 0.0:
            self.failure = "vehicle_collision_radius_m must be finite and positive"
            return
        clearance = math.inf
        closest_obstacle_name: str | None = None
        for obstacle in self.config.get("collision_obstacles", []):
            if not isinstance(obstacle, dict):
                continue
            center = obstacle.get("center", [])
            if not _finite_vector(center):
                continue
            point = (values[0], values[1], values[2])
            obstacle_type = str(obstacle.get("type", "box"))
            if obstacle_type == "box":
                half_extents = obstacle.get("half_extents", [])
                if not _finite_vector(half_extents) or any(float(value) <= 0.0 for value in half_extents):
                    continue
                q = [abs(point[index] - float(center[index])) - float(half_extents[index]) for index in range(3)]
                outside = math.sqrt(sum(max(value, 0.0) ** 2 for value in q))
                signed_distance = outside + min(max(q), 0.0)
            elif obstacle_type == "cylinder":
                radius = float(obstacle.get("radius_m", 0.0))
                half_height = float(obstacle.get("half_height_m", 0.0))
                if not math.isfinite(radius) or not math.isfinite(half_height) or radius <= 0.0 or half_height <= 0.0:
                    continue
                radial_gap = math.hypot(point[0] - float(center[0]), point[1] - float(center[1])) - radius
                vertical_gap = abs(point[2] - float(center[2])) - half_height
                signed_distance = math.hypot(max(radial_gap, 0.0), max(vertical_gap, 0.0)) + min(max(radial_gap, vertical_gap), 0.0)
            else:
                continue
            obstacle_clearance = signed_distance - vehicle_radius
            if obstacle_clearance < clearance:
                clearance = obstacle_clearance
                closest_obstacle_name = str(obstacle.get("name", "")) or None
        if math.isfinite(clearance):
            if (self.minimum_collision_clearance_m is None or
                    clearance < self.minimum_collision_clearance_m):
                self.minimum_collision_clearance_m = clearance
                self.minimum_collision_obstacle_name = closest_obstacle_name
            in_collision = clearance <= 0.0
            if in_collision:
                self.collision_count += 1
            if in_collision and not self._in_collision:
                self.collision_event_count += 1
            self._in_collision = in_collision
        obstacle = self.config.get("pillar_center_enu")
        if int(self.config.get("pillar_waypoint_index", 3)) < 0 or not _finite_vector(obstacle):
            return
        radius = float(self.config.get("pillar_radius_m", 0.55))
        clearance = math.hypot(values[0] - float(obstacle[0]), values[1] - float(obstacle[1])) - radius
        self.actual_min_clearance_m = clearance if self.actual_min_clearance_m is None else min(self.actual_min_clearance_m, clearance)

    @staticmethod
    def _cloud_roi_count(message: Any, *, sensor_frame: bool) -> int:
        """Count finite obstacle samples without retaining a second point cloud."""
        try:
            from sensor_msgs_py import point_cloud2
            count = 0
            for point in point_cloud2.read_points(
                message, field_names=("x", "y", "z"), skip_nans=True
            ):
                x, y, z = (float(point[0]), float(point[1]), float(point[2]))
                if not all(math.isfinite(value) for value in (x, y, z)):
                    continue
                if sensor_frame:
                    # no_path wall is at x=1 and spans y/z; this ROI avoids
                    # using the floor as the obstacle evidence.
                    inside = 0.5 <= x <= 1.6 and abs(y) <= 20.0 and -3.5 <= z <= 8.5
                else:
                    inside = 0.5 <= x <= 1.5 and abs(y) <= 20.0 and 0.0 <= z <= 12.0
                if inside:
                    count += 1
            return count
        except (ImportError, AttributeError, TypeError, ValueError):
            return 0

    def _raw_lidar(self, message: Any) -> None:
        self.raw_lidar_scan_count += 1
        count = self._cloud_roi_count(message, sensor_frame=True)
        self.raw_lidar_roi_max_points = max(self.raw_lidar_roi_max_points, count)
        if count >= 20:
            self.raw_lidar_roi_scan_count += 1
            if self.raw_lidar_roi_scan_count == 1:
                self._record("map_evidence", {
                    "kind": "raw_lidar_obstacle_roi",
                    "points": count,
                    "frame_id": str(message.header.frame_id),
                })

    def _occupied_map(self, message: Any) -> None:
        count = self._cloud_roi_count(message, sensor_frame=False)
        self.occupied_roi_max_points = max(self.occupied_roi_max_points, count)
        if count >= 5:
            self.occupied_scan_count += 1
            if self.occupied_scan_count == 1:
                self._record("map_evidence", {
                    "kind": "occupied_voxel_obstacle_roi",
                    "points": count,
                    "frame_id": str(message.header.frame_id),
                })

    def _update_localization_watchdog(self) -> None:
        if not self.post_takeoff_mode_entered or self.latest_odom is None or self.latest_ground_truth is None:
            return
        if self.latest_odom_stamp_ns is None or self.latest_ground_truth_stamp_ns is None:
            return
        if abs(self.latest_odom_stamp_ns - self.latest_ground_truth_stamp_ns) > 40_000_000:
            return
        lio = self.latest_odom
        truth = self.latest_ground_truth
        if self.lio_gt_origin_offset is None:
            self.lio_gt_origin_offset = tuple(lio[key] - truth[key] for key in ("x", "y", "z"))
            self._record("event", {"name": "ground_truth_watchdog_started"})
            return
        position_error = math.sqrt(sum(
            (lio[key] - truth[key] - self.lio_gt_origin_offset[index]) ** 2
            for index, key in enumerate(("x", "y", "z"))
        ))
        self.max_lio_position_residual_m = max(self.max_lio_position_residual_m, position_error)
        if len(self.lio_position_residual_samples) < 20000:
            self.lio_position_residual_samples.append(position_error)
        velocity_error = math.sqrt(sum(
            (lio[key] - truth[key]) ** 2 for key in ("vx", "vy", "vz")
        ))
        self.max_lio_velocity_residual_m_s = max(
            self.max_lio_velocity_residual_m_s, velocity_error
        )
        # Negative localization profiles must hand control back before the
        # product watchdog's 0.5 m residual limit is crossed.  Keep the
        # nominal watchdog at 0.5 m, but arm the fail-closed harness at 0.45 m
        # so the navigation mode can hand over to POSCTL while the estimator
        # is still inside the acceptance envelope.
        expected_failure = str(self.config.get("expected_outcome", "complete")) == "fail_closed"
        threshold_exceeded = (position_error > (0.45 if expected_failure else 0.5) or
                              velocity_error > 1.0)
        if threshold_exceeded:
            if self.localization_divergence_started_ns is None:
                self.localization_divergence_started_ns = self.sim_now_ns
                self.first_divergence_event = {
                    "classification": "LOCALIZATION_DIVERGENCE",
                    "timestamp_sim_ns": self.sim_now_ns,
                    "position_residual_m": position_error,
                    "velocity_residual_m_s": velocity_error,
                }
                self._record("event", self.first_divergence_event)
            elif (expected_failure or
                  self.sim_now_ns - self.localization_divergence_started_ns >= 500_000_000):
                if not self.localization_divergence_failure:
                    self.localization_divergence_failure = True
                    self.failure = "LOCALIZATION_DIVERGENCE"
                    self._record_handover_request(
                        "localization_divergence",
                        {"position_residual_m": position_error,
                         "velocity_residual_m_s": velocity_error},
                    )
        else:
            self.localization_divergence_started_ns = None

    def _status(self, message: Any) -> None:
        nav_state = int(message.nav_state)
        armed = int(message.arming_state) == int(self.VehicleStatus.ARMING_STATE_ARMED)
        mask = int(message.can_set_nav_states_mask)
        if self.external_mode_id is None:
            for candidate in range(
                int(self.VehicleStatus.NAVIGATION_STATE_EXTERNAL1),
                int(self.VehicleStatus.NAVIGATION_STATE_EXTERNAL8) + 1,
            ):
                if mask & (1 << candidate):
                    self.external_mode_id = candidate
                    event = {"name": "external_mode_discovered", "mode_id": candidate}
                    self.events.append(event)
                    self._record("event", event)
                    break
        mode_was_active = getattr(self, "mode_active", self.mode_entered)
        if self.external_mode_id is not None and nav_state == self.external_mode_id:
            if not mode_was_active:
                event = {"name": "external_mode_entered", "mode_id": self.external_mode_id}
                self.events.append(event)
                self._record("event", event)
                self.mode_entered_sim_ns = self.sim_now_ns
            self.mode_entered = True
            self.mode_active = True
            if (
                getattr(self, "execution", "single_goal") == "mission"
                and getattr(self, "takeoff_requested", False)
                and getattr(self, "takeoff_observed", False)
            ):
                self.post_takeoff_mode_entered = True
        active_before_status = mode_was_active
        if active_before_status and self.exit_requested and int(message.executor_in_charge) == 0 and not self.mode_exit_observed:
            self.mode_exit_observed = True
            self.exit_request_sim_ns = getattr(self, "sim_now_ns", 0)
            event = {"name": "external_mode_exit_observed", "nav_state": nav_state, "executor_in_charge": int(message.executor_in_charge)}
            self.events.append(event)
            self._record("event", event)
        elif active_before_status and nav_state != self.external_mode_id and not self.mode_exit_observed:
            self.mode_exit_observed = True
            self.exit_request_sim_ns = getattr(self, "sim_now_ns", 0)
            event = {"name": "external_mode_exit_observed", "nav_state": nav_state}
            self.events.append(event)
            self._record("event", event)
            self.mode_active = False
            if (
                self.execution == "mission"
                and self.takeoff_observed
                and not self.mission_complete_observed
                and str(self.config.get("expected_outcome", "complete")) != "fail_closed"
            ):
                self.mission_unexpected_exit_observed = True
                self.failure = "External Mode exited before mission completion"
                self._record_handover_request(
                    "unexpected_external_mode_exit",
                    {"nav_state": nav_state,
                     "executor_in_charge": int(message.executor_in_charge)},
                )
        elif active_before_status and nav_state != self.external_mode_id and not self.mode_active:
            self.mode_active = False
        if self.mode_entered and nav_state == int(self.VehicleStatus.NAVIGATION_STATE_AUTO_RTL):
            self.unexpected_rtl = True
        # Keep PX4 failsafe evidence separate from an application handover.
        # A failsafe after a completed mission remains diagnostic evidence but
        # does not retroactively turn a successful mission into a failure.
        if bool(message.failsafe) and not getattr(self, "mission_complete_observed", False):
            self.failsafe_seen = True
        self.armed_seen = self.armed_seen or armed
        self.latest_status = {
            "timestamp_us": int(message.timestamp),
            "arming_state": int(message.arming_state),
            "nav_state": nav_state,
            "failsafe": bool(message.failsafe),
            "pre_flight_checks_pass": bool(message.pre_flight_checks_pass),
            "executor_in_charge": int(message.executor_in_charge),
            "can_set_nav_states_mask": mask,
        }
        if nav_state != self.previous_nav_state:
            self._record("vehicle_status", self.latest_status)
        self.previous_nav_state = nav_state

    def _trajectory(self, message: Any) -> None:
        self.trajectory_received += 1
        if not bool(message.success):
            self.trajectory_failure_count += 1
            same_request = (
                self.latest_trajectory.get("mission_id") == str(message.mission_id) and
                self.latest_trajectory.get("waypoint_index") == int(message.waypoint_index) and
                self.latest_trajectory.get("request_id") == int(message.request_id)
            )
            if same_request and self.latest_trajectory.get("trajectory_role") == 0:
                self.pending_nominal_failure_ns = self.sim_now_ns
            self._record("trajectory_failure", {
                "mission_id": str(message.mission_id),
                "waypoint_index": int(message.waypoint_index),
                "request_id": int(message.request_id),
                "failure_code": int(message.failure_code),
                "world_generation": int(message.world_generation),
                "world_revision": int(message.world_revision),
            })
            return
        self.trajectory_success_count += 1
        role_key = str(int(message.trajectory_role))
        safety_key = str(int(message.safety_plan_kind))
        self.trajectory_role_counts[role_key] = self.trajectory_role_counts.get(role_key, 0) + 1
        self.safety_kind_counts[safety_key] = self.safety_kind_counts.get(safety_key, 0) + 1
        points = [
            (float(point.x), float(point.y), float(point.z)) for point in message.position
        ]
        pillar = self.config.get("pillar_center_enu", [-4.5, 2.5, 3.0])
        pillar_distance = None
        if _finite_vector(pillar):
            pillar_distance = min(
                math.hypot(point[0] - float(pillar[0]), point[1] - float(pillar[1]))
                for point in points
            ) if points else None
        self.latest_trajectory = {
            "mission_id": str(message.mission_id),
            "waypoint_index": int(message.waypoint_index),
            "request_id": int(message.request_id),
            "world_generation": int(message.world_generation),
            "world_revision": int(message.world_revision),
            "duration_s": float(message.duration_s),
            "point_count": len(message.position),
            # Preserve the committed local plan for post-flight visualization
            # and continuity analysis.  The cap keeps scenario.jsonl bounded
            # even if a planner publishes an unexpectedly dense trajectory.
            "position_points": [list(point) for point in points[:512]],
            "velocity_points": [
                [float(vector.x), float(vector.y), float(vector.z)]
                for vector in list(message.velocity)[:512]
            ],
            "pillar_min_distance_m": pillar_distance,
            "trajectory_role": int(message.trajectory_role),
            "safety_plan_kind": int(message.safety_plan_kind),
        }
        self.trajectory_history.append(dict(self.latest_trajectory))
        if len(self.trajectory_history) > 4096:
            del self.trajectory_history[:len(self.trajectory_history) - 4096]
        if int(message.trajectory_role) == 1 and self.pending_nominal_failure_ns is not None:
            self.safety_transition_count += 1
            self.fallback_latencies_ms.append(
                max(0.0, (self.sim_now_ns - self.pending_nominal_failure_ns) / 1e6)
            )
            self.pending_nominal_failure_ns = None
        elif int(message.trajectory_role) != 1:
            # A retry that returns to nominal execution is not a fallback;
            # do not let a later unrelated safety trajectory inherit it.
            self.pending_nominal_failure_ns = None
        record_key = (self.latest_trajectory["mission_id"], self.latest_trajectory["waypoint_index"])
        if self.execution == "mission" and self.latest_trajectory["waypoint_index"] >= 0:
            record_index = self._trajectory_record_indices.get(record_key)
            if record_index is None:
                self._trajectory_record_indices[record_key] = len(self.trajectory_records)
                self.trajectory_records.append(dict(self.latest_trajectory))
            else:
                self.trajectory_records[record_index] = dict(self.latest_trajectory)
        elif len(self.trajectory_records) < 128:
            self.trajectory_records.append(dict(self.latest_trajectory))
        self._record("trajectory", self.latest_trajectory)

    def _planner_trace(self, message: Any) -> None:
        """Persist one explicit rolling-planner cycle without synthesizing IDs."""
        endpoint = getattr(message, "horizon_endpoint", None)
        raw = {
            "planning_cycle_id": getattr(message, "cycle_id", None),
            "bundle_id": getattr(message, "bundle_id", None),
            "request_id": getattr(message, "request_id", None),
            "world_generation": getattr(message, "world_generation", None),
            "world_revision": getattr(message, "world_revision", None),
            "route_id": getattr(message, "route_id", None),
            "route_candidate_count": getattr(message, "route_candidate_count", None),
            "corridor_region_count": getattr(message, "corridor_region_count", None),
            "horizon_start_arc_m": getattr(message, "horizon_start_arc_m", None),
            "horizon_end_arc_m": getattr(message, "horizon_end_arc_m", None),
            "horizon_endpoint": endpoint,
            "planning_state_position": getattr(message, "planning_state_position", None),
            "planning_state_velocity": getattr(message, "planning_state_velocity", None),
            "planning_horizon_distance_m": getattr(message, "planning_horizon_distance_m", None),
            "horizon_forward_projection_m": getattr(message, "horizon_forward_projection_m", None),
            "horizon_progress_m": getattr(message, "horizon_progress_m", None),
            "known_free_horizon_m": getattr(message, "known_free_horizon_m", None),
            "horizon_ray_occupied": getattr(message, "horizon_ray_occupied", None),
            "selected_branch": getattr(message, "selected_branch", None),
            "status": getattr(message, "status", None),
            "failure_code": getattr(message, "failure_code", None),
            "planning_latency_ms": getattr(message, "planning_latency_ms", None),
            "optimizer_latency_ms": getattr(message, "optimizer_latency_ms", None),
            "maximum_velocity_mps": getattr(message, "maximum_velocity_mps", None),
            "maximum_acceleration_mps2": getattr(message, "maximum_acceleration_mps2", None),
            "maximum_jerk_mps3": getattr(message, "maximum_jerk_mps3", None),
            "splice_position_residual_m": getattr(message, "splice_position_residual_m", None),
            "splice_velocity_residual_mps": getattr(message, "splice_velocity_residual_mps", None),
            "splice_acceleration_residual_mps2": getattr(message, "splice_acceleration_residual_mps2", None),
        }
        if endpoint is not None:
            raw["horizon_endpoint"] = [
                getattr(endpoint, "x", None),
                getattr(endpoint, "y", None),
                getattr(endpoint, "z", None),
            ]
        record = normalize_planner_trace_record(
            raw,
            source="ros:/navigation/planner_trace",
            timestamp_s=(
                _time_ns(message.header.stamp) / 1e9
                if hasattr(message, "header") and hasattr(message.header, "stamp")
                else None
            ),
        )
        if record is None:
            return
        self.planner_trace_records.append(record)
        if len(self.planner_trace_records) > 4096:
            del self.planner_trace_records[:len(self.planner_trace_records) - 4096]
        self._record("planner_trace", record)

    def _mission_complete(self, message: Any) -> None:
        if bool(message.data):
            self.mission_complete_observed = True
            self._record("event", {"name": "mission_complete_observed"})

    def _mode_status(self, message: Any) -> None:
        self.mode_status_state = int(message.state)
        self.mode_status_reason = int(message.reason)
        record = {
            "state": self.mode_status_state,
            "state_name": _MODE_STATUS_NAMES.get(self.mode_status_state, "UNKNOWN"),
            "reason": self.mode_status_reason,
            "reason_name": _MODE_STATUS_REASON_NAMES.get(self.mode_status_reason, "UNKNOWN"),
            "mission_id": str(message.mission_id),
            "waypoint_index": int(message.waypoint_index),
            "request_id": int(message.request_id),
            "waypoint_accepted": bool(message.waypoint_accepted),
            "accepted_waypoint_index": int(message.accepted_waypoint_index),
            "acceptance_position_error_m": float(message.acceptance_position_error_m),
            "acceptance_speed_mps": float(message.acceptance_speed_mps),
        }
        if record["waypoint_accepted"]:
            self.waypoint_acceptance_events.append(record)
            self._record("waypoint_accepted", record)
        self._record("navigation_mode_status", record)

    def _mode_completed(self, message: Any) -> None:
        if self.external_mode_id is None or int(message.nav_state) != self.external_mode_id:
            return
        self.mode_completion_result = int(message.result)
        self.mode_failure_observed = self.mode_completion_result == 100
        if (
            self.mode_failure_observed
            and self.execution == "mission"
            and not self.mission_complete_observed
        ):
            expected_failure = str(self.config.get("expected_outcome", "complete")) == "fail_closed"
            if expected_failure:
                # A fail-closed mission is expected to terminate the mode after
                # the planner/safety contract refuses an unusable route.  Keep
                # this separate from an unexpected runtime exit so the harness
                # can validate the safety outcome instead of reporting a false
                # scenario failure.
                self._record("event", {"name": "expected_fail_closed"})
            else:
                self.mission_unexpected_exit_observed = True
                self.failure = "External Mode completed with failure before mission completion"
            self._record("event", {
                "name": "external_mode_failure_handover",
                "mode_completion_result": self.mode_completion_result,
                "expected_fail_closed": expected_failure,
            })
        self._record("event", {
            "name": "external_mode_completed",
            "nav_state": int(message.nav_state),
            "result": self.mode_completion_result,
        })

    def _record_handover_request(
        self, trigger: str = "terminal_mode_failure",
        detail: dict[str, Any] | None = None,
    ) -> None:
        """Record a requested POSCTL handover; never issue LAND or disarm."""
        if self.execution != "mission":
            return
        detail = dict(detail or {})
        event = {
            "name": "position_control_handover_requested",
            "trigger": trigger,
            "detail": detail,
        }
        self.events.append(event)
        self._record("event", event)

    def _finish_or_wait(self, reason: str) -> None:
        self.terminal_outcome = reason
        if self.interactive_handover:
            if not self.handover_waiting:
                self.handover_waiting = True
                self._record("event", {
                    "name": "interactive_handover_waiting",
                    "outcome": reason,
                })
            return
        self.finish(reason)

    def _post_takeoff_mode_exit_observed(self) -> bool:
        """Return true only for an exit belonging to the airborne activation."""
        return (
            self.post_takeoff_mode_entered and
            self.mode_exit_observed and
            self.mode_entered_sim_ns is not None and
            self.exit_request_sim_ns is not None and
            self.exit_request_sim_ns >= self.mode_entered_sim_ns
        )

    def _goal(self, message: Any) -> None:
        self.goal_received_count += 1
        waypoint_index = int(message.waypoint_index)
        if not self.goal_indices or self.goal_indices[-1] != waypoint_index:
            self.goal_indices.append(waypoint_index)
        self.latest_goal = {
            "mission_id": str(message.mission_id),
            "waypoint_index": waypoint_index,
            "request_id": int(message.request_id),
            "frame_id": str(message.header.frame_id),
            "x": float(message.target.x),
            "y": float(message.target.y),
            "z": float(message.target.z),
        }
        self._record("goal", self.latest_goal)

    def _local_position(self, message: Any) -> None:
        speed = math.sqrt(sum(float(value) ** 2 for value in (message.vx, message.vy, message.vz)))
        if math.isfinite(speed):
            self.measured_speed_samples.append(speed)
        self.latest_local_position = {
            "z_ned_m": float(message.z),
            "vx_ned_m_s": float(message.vx),
            "vy_ned_m_s": float(message.vy),
            "vz_ned_m_s": float(message.vz),
        }
    def _land_detected(self, message: Any) -> None:
        # Never infer a ground latch from altitude or speed. PX4's landed bit
        # is the only authoritative ground indication in this harness.
        self.landed_detector_current = bool(message.landed)
        if self.landed_detector_current:
            self.grounded_observed = True
        self._record("land_detected", {
            "landed": bool(message.landed),
            "maybe_landed": bool(message.maybe_landed),
            "ground_contact": bool(message.ground_contact),
        })

    def _setpoint(self, message: Any) -> None:
        self.setpoint_count += 1
        velocity_finite = _finite_vector(message.velocity)
        if velocity_finite:
            speed = math.sqrt(sum(float(value) ** 2 for value in message.velocity))
            if math.isfinite(speed):
                self.setpoint_speed_samples.append(speed)
        position_unset = all(math.isnan(float(value)) for value in message.position)
        position_finite = _finite_vector(message.position)
        acceleration_unset = all(math.isnan(float(value)) for value in message.acceleration)
        # External Mode may use PX4's position controller with a bounded
        # velocity feed-forward.  Accept both velocity-only and the valid
        # position+velocity combination; a partially finite position vector is
        # still rejected as malformed.
        acceleration_finite = _finite_vector(message.acceleration)
        finite = (
            velocity_finite and (position_unset or position_finite) and
            (acceleration_unset or acceleration_finite)
        )
        if finite:
            self.finite_setpoint_count += 1
        if self.setpoint_count == 1 or self.setpoint_count % 50 == 0:
            self._record("setpoint", {
                "finite": finite,
                "velocity_finite": velocity_finite,
                "position_unset": position_unset,
                "position_finite": position_finite,
                "acceleration_unset": acceleration_unset,
                "position_ned": _json_vector(message.position),
                "velocity_ned": _json_vector(message.velocity),
                "acceleration_ned": _json_vector(message.acceleration),
            })

    def _ack(self, message: Any) -> None:
        self.ack_count += 1
        record = {"command": int(message.command), "result": int(message.result)}
        self.command_acks.append(record)
        if (int(message.command) == int(self.VehicleCommand.VEHICLE_CMD_COMPONENT_ARM_DISARM)
                and int(message.result) == 0):
            self.arm_ack_success_sim_ns = self.sim_now_ns
        self._record("command_ack", record)

    def sim_elapsed_s(self) -> float:
        if self.sim_start_ns is None:
            return 0.0
        return max(0.0, (self.sim_now_ns - self.sim_start_ns) / 1e9)

    def _command(self, name: str, command: int, p1: float = 0.0, p7: float = 0.0) -> None:
        message = self.VehicleCommand()
        message.timestamp = self.sim_now_ns // 1000
        message.command = command
        message.param1 = p1
        message.param7 = p7
        message.target_system = 1
        message.target_component = 1
        message.source_system = 1
        message.source_component = 1
        message.from_external = True
        self.command_pub.publish(message)
        event = {"name": name, "command": command, "param1": p1, "param7": p7}
        self.events.append(event)
        self._record("command", event)

    def _takeoff(self, altitude_m: float) -> None:
        """Match px4_ros2 ModeExecutor::takeoff command field semantics."""
        message = self.VehicleCommand()
        message.timestamp = self.sim_now_ns // 1000
        message.command = self.VehicleCommand.VEHICLE_CMD_NAV_TAKEOFF
        message.param1 = math.nan
        message.param2 = math.nan
        message.param3 = math.nan
        message.param4 = math.nan
        message.param5 = math.nan
        message.param6 = math.nan
        message.param7 = altitude_m
        message.target_system = 1
        message.target_component = 1
        message.source_system = 1
        message.source_component = 1
        message.from_external = True
        self.command_pub.publish(message)
        event = {
            "name": "takeoff",
            "command": int(message.command),
            "param7": altitude_m,
        }
        self.events.append(event)
        self._record("command", event)
        self.takeoff_requested_sim_ns = self.sim_now_ns

    def _retry(self, name: str, command: int, p1: float = 0.0) -> None:
        period_ns = int(float(self.config.get("command_retry_period_s", 1.0)) * 1e9)
        if self.sim_now_ns - self.last_command_ns.get(name, -10**18) >= period_ns:
            self._command(name, command, p1)
            self.last_command_ns[name] = self.sim_now_ns

    def _publish_fixture_trajectory(self) -> None:
        from navigation_interfaces.msg import PlannedTrajectory

        position = self.latest_odom or {"x": 0.0, "y": 0.0, "z": 0.0}
        trajectory = PlannedTrajectory()
        trajectory.header.frame_id = "lio_odom"
        trajectory.header.stamp.sec = self.sim_now_ns // 1_000_000_000
        trajectory.header.stamp.nanosec = self.sim_now_ns % 1_000_000_000
        # Keep the fixture on the same trajectory contract as the production
        # runtime. The PX4 adapter rejects successful trajectories without an
        # id and otherwise treats a zero valid_from as a legacy phase reset.
        trajectory.valid_from = trajectory.header.stamp
        trajectory.trajectory_id = 1
        trajectory.commitment_horizon_s = 0.0
        trajectory.success = True
        trajectory.world_generation = 1
        trajectory.world_revision = 0
        trajectory.duration_s = 1.0
        trajectory.time_from_start = [0.0, 1.0]
        trajectory.position = [self.Point(), self.Point()]
        trajectory.velocity = [self.Vector3(), self.Vector3()]
        trajectory.acceleration = [self.Vector3(), self.Vector3()]
        for point in trajectory.position:
            point.x = position["x"]
            point.y = position["y"]
            point.z = position["z"]
        self.trajectory_pub.publish(trajectory)
        self.last_trajectory_ns = self.sim_now_ns

    def _publish_planner_goal(self) -> None:
        if self.latest_odom is None:
            return
        offset = self.config.get("goal_offset_m", [1.0, 0.0, 0.0])
        if not _finite_vector(offset):
            self.failure = "planner goal_offset_m must contain three finite values"
            self.finish("INVALID_GOAL_CONFIGURATION")
            return
        goal = {
            "x": self.latest_odom["x"] + float(offset[0]),
            "y": self.latest_odom["y"] + float(offset[1]),
            "z": self.latest_odom["z"] + float(offset[2]),
        }
        message = self.NavigationGoal()
        message.header.frame_id = str(self.config.get("planning_frame", "lio_odom"))
        message.header.stamp.sec = self.sim_now_ns // 1_000_000_000
        message.header.stamp.nanosec = self.sim_now_ns % 1_000_000_000
        message.mission_id = str(self.config.get("mission_id", "external_mode_smoke"))
        message.waypoint_index = 0
        self.goal_request_id += 1
        message.request_id = self.goal_request_id
        message.target.x = goal["x"]
        message.target.y = goal["y"]
        message.target.z = goal["z"]
        message.acceptance_radius_m = float(self.config.get("acceptance_radius_m", 0.5))
        self.goal_pub.publish(message)
        self.goal_publish_count += 1
        self.latest_goal = goal
        self.last_goal_ns = self.sim_now_ns
        self._record("goal", {"frame_id": message.header.frame_id, **goal})

    def _tick(self) -> None:
        if self.finished:
            return
        if getattr(self, "handover_waiting", False):
            return
        if time.monotonic() - self.wall_start > float(self.config.get("wall_timeout_s", 120.0)):
            self.failure = "scenario wall timeout"
            self.finish("WALL_TIMEOUT")
            return
        if self.sim_start_ns is None:
            return
        elapsed = self.sim_elapsed_s()
        mission_mode = getattr(self, "execution", "single_goal") == "mission"
        expected_failure = str(self.config.get("expected_outcome", "complete")) == "fail_closed"
        if not mission_mode:
            trajectory_period_ns = int(float(self.config.get("trajectory_publish_period_s", 0.2)) * 1e9)
            trajectory_source = self.config.get("trajectory_source", "planner")
            if trajectory_source == "fixture" and self.sim_now_ns - self.last_trajectory_ns >= trajectory_period_ns:
                self._publish_fixture_trajectory()
            elif trajectory_source == "planner" and not self.exit_requested and (
                self.sim_now_ns - self.last_goal_ns >= trajectory_period_ns
            ):
                self._publish_planner_goal()
            elif trajectory_source not in {"fixture", "planner", "none"}:
                self.failure = f"unsupported trajectory source: {trajectory_source}"
                self.finish("INVALID_TRAJECTORY_SOURCE")
                return

        activation_timeout_s = float(self.config.get("activation_timeout_s", 30.0))
        if self.external_mode_id is None and elapsed > activation_timeout_s:
            self.failure = "PX4 did not advertise a registered External Mode"
            self.finish("ACTIVATION_TIMEOUT")
            return

        if mission_mode:
            takeoff_altitude_m = float(self.config.get("takeoff_altitude_m", 3.0))
            if not math.isfinite(takeoff_altitude_m) or takeoff_altitude_m <= 0.5:
                self.failure = "takeoff_altitude_m must be finite and above 0.5 m"
                self.finish("INVALID_TAKEOFF_CONFIGURATION")
                return
            if self.external_mode_id is None:
                return
            stable_s = float(self.config.get("takeoff_stable_s", 2.0))
            stable_elapsed_s = (
                0.0 if self.takeoff_stable_since_ns is None else
                max(0.0, (self.sim_now_ns - self.takeoff_stable_since_ns) / 1e9)
            )
            takeoff_elapsed_s = (
                0.0 if self.takeoff_requested_sim_ns is None else
                max(0.0, (self.sim_now_ns - self.takeoff_requested_sim_ns) / 1e9)
            )
            # Select the registered mode so its external-vision arming check
            # participates in PX4's contract.  After a successful arm ACK we
            # wait one scheduler settle window before NAV_TAKEOFF; issuing both
            # commands in the same tick is intermittently ignored by SITL.
            # Keep the legacy contract marker ``if not self.armed_seen:`` in
            # this block: the harness tests and downstream audit scripts use
            # it to delimit the automatic-arm phase.
            if self.manual_takeoff:
                if not self.armed_seen:
                    if elapsed > activation_timeout_s:
                        self.failure = "manual arm/takeoff was not observed before timeout"
                        self.finish("MANUAL_ARM_TIMEOUT")
                    return
            if self.arm_ack_success_sim_ns is None and not self.manual_takeoff:
                if not self.mode_entered:
                    self._retry(
                        "activate_external_mode", self.VehicleCommand.VEHICLE_CMD_SET_NAV_STATE,
                        float(self.external_mode_id))
                    return
                # PX4 is authoritative through its command ACK. The aggregate
                # pre-flight bit can remain false until the successful arm in
                # this external-vision configuration, so it cannot gate the
                # retry. Use a deliberately slow cadence to avoid flooding
                # commands while EKF heading/health converges.  Do not gate
                # this on mode_entered: the vehicle must be armed before the
                # external executor is selected.
                arm_retry_ns = int(float(
                    self.config.get("arm_retry_period_s", 5.0)) * 1e9)
                if self.sim_now_ns - self.last_command_ns.get("arm", -10**18) >= arm_retry_ns:
                    self._command(
                        "arm", self.VehicleCommand.VEHICLE_CMD_COMPONENT_ARM_DISARM, 1.0)
                    self.last_command_ns["arm"] = self.sim_now_ns
                if elapsed > activation_timeout_s:
                    self.failure = "PX4 did not arm before mission takeoff"
                    self.finish("ARM_TIMEOUT")
                return
            if not self.takeoff_requested:
                if not self.manual_takeoff:
                    # The ACK confirms that PX4 accepted the arm request, but
                    # the vehicle_status transition can lag by a few scheduler
                    # ticks. Give commander one settle window before sending
                    # TAKEOFF; sending both in the same tick is intermittently
                    # ignored by SITL and causes auto-preflight disarm.
                    settle_ns = int(float(self.config.get("takeoff_mode_settle_s", 1.0)) * 1e9)
                    if self.sim_now_ns - self.arm_ack_success_sim_ns < settle_ns:
                        return
                    self._takeoff(takeoff_altitude_m)
                self.takeoff_requested = True
                self.takeoff_requested_sim_ns = self.sim_now_ns
                return
            if self.takeoff_requested and not self.takeoff_observed:
                z_ned = self.latest_local_position.get("z_ned_m")
                speeds = [self.latest_local_position.get(name) for name in (
                    "vx_ned_m_s", "vy_ned_m_s", "vz_ned_m_s")]
                airborne = (
                    z_ned is not None and math.isfinite(float(z_ned)) and
                    float(z_ned) <= -0.9 * takeoff_altitude_m and
                    all(value is not None and math.isfinite(float(value)) and abs(float(value)) < 0.5
                        for value in speeds)
                )
                if airborne:
                    self.takeoff_observed = True
                    self.takeoff_stable_since_ns = self.sim_now_ns
                elif takeoff_elapsed_s > float(self.config.get("takeoff_timeout_s", 45.0)):
                    self.failure = "vehicle did not reach stable takeoff altitude"
                    self.finish("TAKEOFF_TIMEOUT")
                else:
                    return
            # Re-arm the stability window whenever the vehicle is still moving.
            # Reaching altitude alone is not sufficient for a safe handover:
            # the first planner cycle must have a usable stop envelope even
            # when the current voxel is inside the LiDAR shadow.
            stable_speed_limit = float(
                self.config.get("takeoff_stable_speed_mps", 0.15))
            stable_speeds = [self.latest_local_position.get(name) for name in (
                "vx_ned_m_s", "vy_ned_m_s", "vz_ned_m_s")]
            stable_velocity = (
                all(value is not None and math.isfinite(float(value))
                    for value in stable_speeds) and
                math.sqrt(sum(float(value) ** 2 for value in stable_speeds)) <= stable_speed_limit)
            if not stable_velocity:
                self.takeoff_stable_since_ns = self.sim_now_ns
                self.pre_activation_ready_since_ns = None
                return

            # A GUI run can briefly starve DDS while Gazebo/RViz compile and
            # render. Do not hand control to External Mode on a single fresh
            # sample after such a gap: require a continuous window of fresh
            # propagated LIO odometry first.
            odometry_max_age_s = float(
                self.config.get("pre_activation_odometry_max_age_s", 0.10))
            odometry_stable_s = float(
                self.config.get("pre_activation_odometry_stable_s", 1.0))
            odometry_age_s = (
                math.inf if self.latest_odom_stamp_ns is None else
                (self.sim_now_ns - self.latest_odom_stamp_ns) / 1e9
            )
            odometry_fresh = (
                math.isfinite(odometry_age_s) and
                -0.05 <= odometry_age_s <= odometry_max_age_s
            )
            if not odometry_fresh:
                self.pre_activation_ready_since_ns = None
                return
            if self.pre_activation_ready_since_ns is None:
                self.pre_activation_ready_since_ns = self.sim_now_ns
                return
            odometry_ready_elapsed_s = max(
                0.0, (self.sim_now_ns - self.pre_activation_ready_since_ns) / 1e9)
            if not getattr(self, "mode_active", False) and not (
                    self.mission_complete_observed or
                    (expected_failure and self._post_takeoff_mode_exit_observed()) or
                    (expected_failure and self.mode_failure_observed) or
                    self.mission_unexpected_exit_observed):
                if stable_elapsed_s < stable_s or odometry_ready_elapsed_s < odometry_stable_s:
                    return
                self.mode_exit_observed = False
                self.exit_request_sim_ns = None
                if self.navigation_activation_started_sim_ns is None:
                    self.navigation_activation_started_sim_ns = self.sim_now_ns
                self._retry(
                    "activate_external_mode", self.VehicleCommand.VEHICLE_CMD_SET_NAV_STATE,
                    float(self.external_mode_id))
                activation_elapsed_s = max(
                    0.0,
                    (self.sim_now_ns - self.navigation_activation_started_sim_ns) / 1e9,
                )
                if activation_elapsed_s > activation_timeout_s:
                    self.failure = "PX4 did not enter External Mode after stable takeoff"
                    self.mission_unexpected_exit_observed = True
                    self._record_handover_request(
                        "airborne_activation_timeout",
                        {"odometry_age_s": odometry_age_s},
                    )
                return
            if stable_elapsed_s < stable_s:
                return
            posctl = int(self.VehicleStatus.NAVIGATION_STATE_POSCTL)
            if self.localization_divergence_failure:
                # A mission-complete message cannot erase a component-level
                # localization failure that was observed earlier in the same
                # activation.  Keep the terminal outcome distinct so the
                # headless contract returns exit 1 instead of reporting a
                # misleading COMPLETE.
                self._finish_or_wait("FAILED_COMPONENT")
                return
            if self.mission_complete_observed:
                # Completion is a terminal mission result.  The executor has
                # already issued the POSCTL handover; PX4 may reject that
                # command while its own health gate is still settling.  Do
                # not hold a headless run open forever or infer LAND/disarm
                # from that external transition result.
                self._finish_or_wait("COMPLETE")
                return
            if self.mode_status_state == int(self.NavigationModeStatus.FAILED):
                if int(self.latest_status.get("nav_state", -1)) == posctl:
                    self._finish_or_wait("FAILED_COMPONENT")
                return
            if self.mode_status_state == int(self.NavigationModeStatus.PAUSED):
                if self.mode_status_reason == int(self.NavigationModeStatus.SAFETY_STOP):
                    # A POSCTL request can be rejected by PX4's own health
                    # gate.  The mode has still completed the safety contract
                    # and is intentionally holding; do not turn that benign
                    # rejection into a wall timeout or a component failure.
                    self._finish_or_wait("PAUSED_SAFETY_STOP")
                    return
                if int(self.latest_status.get("nav_state", -1)) == posctl:
                    self._finish_or_wait("PAUSED_SAFETY_STOP")
                return
            if self.mode_exit_observed:
                if int(self.latest_status.get("nav_state", -1)) == posctl:
                    self.operator_aborted = True
                    self._finish_or_wait("ABORTED_OPERATOR")
                return
            mode_elapsed_s = (
                0.0 if self.mode_entered_sim_ns is None else
                max(0.0, (self.sim_now_ns - self.mode_entered_sim_ns) / 1e9)
            )
            if mode_elapsed_s > float(self.config.get("mission_timeout_s", 90.0)):
                self.failure = "mission did not complete and External Mode did not hand over"
                self.finish("MISSION_TIMEOUT")
            return

        if self.trajectory_success_count == 0:
            if elapsed > activation_timeout_s:
                self.failure = "navigation runtime did not publish a successful trajectory"
                self.finish("TRAJECTORY_TIMEOUT")
            return
        if not self.mode_entered:
            if self.external_mode_id is None:
                if elapsed > float(self.config.get("activation_timeout_s", 30.0)):
                    self.failure = "PX4 did not advertise a registered External Mode"
                    self.finish("ACTIVATION_TIMEOUT")
                return
            self._retry("activate_external_mode", self.VehicleCommand.VEHICLE_CMD_SET_NAV_STATE, float(self.external_mode_id))
            if elapsed > activation_timeout_s:
                self.failure = "PX4 did not enter the registered External Mode"
                self.finish("ACTIVATION_TIMEOUT")
            return
        if not self.armed_seen:
            # Let PX4 evaluate its complete arming contract. In this headless
            # setup the status bit can remain false while the registered
            # External Mode and its custom arming check are already valid;
            # pre-filtering here hides the actual command/ack outcome.
            self._retry("arm", self.VehicleCommand.VEHICLE_CMD_COMPONENT_ARM_DISARM, 1.0)
            if elapsed > float(self.config.get("activation_timeout_s", 30.0)):
                self.failure = "PX4 did not arm after External Mode activation"
                self.finish("ARM_TIMEOUT")
            return
        mode_elapsed_s = (
            0.0
            if self.mode_entered_sim_ns is None
            else max(0.0, (self.sim_now_ns - self.mode_entered_sim_ns) / 1e9)
        )
        if (
            self.armed_seen
            and not self.exit_requested
            and mode_elapsed_s >= float(self.config.get("post_activation_s", 8.0))
        ):
            exit_state = float(self.config.get("exit_nav_state", self.VehicleStatus.NAVIGATION_STATE_AUTO_LOITER))
            self._command("exit_external_mode", self.VehicleCommand.VEHICLE_CMD_SET_NAV_STATE, exit_state)
            self.exit_requested = True
            self.exit_request_sim_ns = self.sim_now_ns
            return
        if self.mode_exit_observed and int(self.latest_status.get("nav_state", -1)) == int(self.VehicleStatus.NAVIGATION_STATE_POSCTL):
            self._finish_or_wait("ABORTED_OPERATOR")

    def finish(self, reason: str) -> None:
        if self.finished:
            return
        self.finished = True
        failures = [self.failure] if self.failure else []
        expected_outcome = str(self.config.get("expected_outcome", "complete"))
        if self.external_mode_id is None:
            failures.append("External Mode id was not discovered")
        if expected_outcome == "complete" and self.trajectory_success_count <= 0:
            failures.append("no successful PlannedTrajectory observed")
        if not self.mode_entered:
            failures.append("External Mode was never entered")
        if self.setpoint_count <= 0:
            failures.append("no PX4 TrajectorySetpoint observed")
        if self.setpoint_count > 0 and self.finite_setpoint_count != self.setpoint_count:
            failures.append("PX4 TrajectorySetpoint contained non-finite values")
        # A safety pause is an intentional terminal handover state even when
        # PX4 rejects the POSCTL request because its own health gate is still
        # false.  Do not report that expected pause as an unobserved mode exit.
        mode_stopped = self.mode_exit_observed or self.mission_unexpected_exit_observed or (
            self.terminal_outcome in {"COMPLETE", "PAUSED_SAFETY_STOP", "ABORTED_OPERATOR"}
        ) or (
            expected_outcome == "fail_closed" and self.mode_failure_observed
        )
        if not mode_stopped:
            failures.append("External Mode exit was not observed")
        if self.failsafe_seen:
            failures.append("PX4 reported failsafe during External Mode acceptance")
        if self.unexpected_rtl:
            failures.append("unexpected RTL observed during External Mode acceptance")
        if self.localization_divergence_failure:
            failures.append("LOCALIZATION_DIVERGENCE watchdog terminated the mission")
        if expected_outcome == "complete" and self.execution == "mission":
            expected_count = int(self.config.get("mission_waypoint_count", 0))
            expected_indices = list(range(max(0, expected_count)))
            accepted_indices = [
                int(item["accepted_waypoint_index"])
                for item in self.waypoint_acceptance_events
                if bool(item.get("waypoint_accepted", False))
            ]
            allow_initial_skip = bool(self.config.get("allow_initial_pass_through_skip", False))
            valid_acceptance = accepted_indices == expected_indices or (
                allow_initial_skip and bool(expected_indices) and
                accepted_indices == expected_indices[1:]
            )
            if not self.mission_complete_observed:
                failures.append("mission completion event was not observed")
            if expected_count <= 0:
                failures.append("mission_waypoint_count is not configured")
            elif not valid_acceptance:
                failures.append(
                    "waypoint acceptance coverage incomplete: "
                    f"expected {expected_indices}, got {accepted_indices}"
                )
        if expected_outcome != "fail_closed":
            residual_p95 = _percentile(self.lio_position_residual_samples, 0.95)
            if residual_p95 is not None and residual_p95 > 0.35:
                failures.append("LIO position residual p95 exceeded 0.35 m")
            if self.max_lio_position_residual_m >= 0.5:
                failures.append("LIO position residual exceeded 0.5 m watchdog")
        summary = {
            "reason": reason,
            "outcome": self.terminal_outcome or reason,
            "expected_outcome": expected_outcome,
            "map_seed": self.config.get("map_seed", 0),
            "duration_s": self.sim_elapsed_s(),
            "wall_elapsed_s": time.monotonic() - self.wall_start,
            "external_mode_id": self.external_mode_id,
            "trajectory_received": self.trajectory_received,
            "trajectory_success_count": self.trajectory_success_count,
            "trajectory_failure_count": self.trajectory_failure_count,
            "trajectory_role_counts": self.trajectory_role_counts,
            "safety_kind_counts": self.safety_kind_counts,
            "speed_metrics": {
                "setpoint_mps": {
                    "count": len(self.setpoint_speed_samples),
                    "p50": _percentile(self.setpoint_speed_samples, 0.50),
                    "p95": _percentile(self.setpoint_speed_samples, 0.95),
                    "maximum": max(self.setpoint_speed_samples, default=None),
                },
                "measured_mps": {
                    "count": len(self.measured_speed_samples),
                    "p50": _percentile(self.measured_speed_samples, 0.50),
                    "p95": _percentile(self.measured_speed_samples, 0.95),
                    "maximum": max(self.measured_speed_samples, default=None),
                },
            },
            "safety_transition_count": self.safety_transition_count,
            "fallback_latency_ms": {
                "count": len(self.fallback_latencies_ms),
                "p50": sorted(self.fallback_latencies_ms)[len(self.fallback_latencies_ms) // 2] if self.fallback_latencies_ms else None,
                "max": max(self.fallback_latencies_ms, default=None),
            },
            "actual_min_clearance_m": self.actual_min_clearance_m,
            "minimum_collision_clearance_m": self.minimum_collision_clearance_m,
            "minimum_collision_obstacle_name": self.minimum_collision_obstacle_name,
            "collision_count": self.collision_count,
            "collision_event_count": self.collision_event_count,
            "localization_watchdog": {
                "origin_offset_m": list(self.lio_gt_origin_offset) if self.lio_gt_origin_offset else None,
                "first_divergence": self.first_divergence_event,
                "max_position_residual_m": self.max_lio_position_residual_m,
                "p95_position_residual_m": _percentile(self.lio_position_residual_samples, 0.95),
                "max_velocity_residual_m_s": self.max_lio_velocity_residual_m_s,
                "fail_closed_trigger_m": 0.45 if expected_outcome == "fail_closed" else 0.5,
                "failure": self.localization_divergence_failure,
            },
            "obstacle_evidence": {
                "raw_lidar_scan_count": self.raw_lidar_scan_count,
                "raw_lidar_roi_scan_count": self.raw_lidar_roi_scan_count,
                "raw_lidar_roi_max_points": self.raw_lidar_roi_max_points,
                "occupied_scan_count": self.occupied_scan_count,
                "occupied_roi_max_points": self.occupied_roi_max_points,
            },
            "latest_trajectory": self.latest_trajectory,
            "trajectory_records": self.trajectory_records,
            "trajectory_history": self.trajectory_history,
            "planner_trace_records": self.planner_trace_records,
            "goal_publish_count": self.goal_publish_count,
            "goal_received_count": self.goal_received_count,
            "goal_indices": self.goal_indices,
            "waypoint_acceptance_events": self.waypoint_acceptance_events,
            "latest_goal": self.latest_goal,
            "setpoint_count": self.setpoint_count,
            "finite_setpoint_count": self.finite_setpoint_count,
            "command_ack_count": self.ack_count,
            "command_acks": self.command_acks,
            "external_mode_entered": self.mode_entered,
            "external_mode_exit_observed": self.mode_exit_observed,
            "mode_completion_result": self.mode_completion_result,
            "mode_failure_observed": self.mode_failure_observed,
            "mission_unexpected_exit_observed": self.mission_unexpected_exit_observed,
            "mission_complete_observed": self.mission_complete_observed,
            "mode_status_state": self.mode_status_state,
            "mode_status_state_name": _MODE_STATUS_NAMES.get(self.mode_status_state, "UNKNOWN"),
            "mode_status_reason": self.mode_status_reason,
            "mode_status_reason_name": _MODE_STATUS_REASON_NAMES.get(self.mode_status_reason, "UNKNOWN"),
            "armed": self.armed_seen,
            "takeoff_requested": self.takeoff_requested,
            "manual_takeoff": self.manual_takeoff,
            "takeoff_observed": self.takeoff_observed,
            "land_requested": False,
            "land_requested_sim_ns": None,
            "land_trigger": None,
            "land_trigger_detail": {},
            "grounded_observed": self.grounded_observed,
            "landed_detector_current": self.landed_detector_current,
            "pre_flight_checks_pass": bool(self.latest_status.get("pre_flight_checks_pass", False)),
            "disarm_successful": False,
            "failsafe_seen": self.failsafe_seen,
            "unexpected_rtl": self.unexpected_rtl,
            "events": self.events,
            "failures": failures,
        }
        if self.execution == "mission":
            expected_count = int(self.config.get("mission_waypoint_count", 0))
            expected_indices = list(range(expected_count))
            if expected_outcome == "fail_closed":
                if self.mission_complete_observed:
                    failures.append("fail-closed scenario unexpectedly completed mission")
                safety_pause_observed = (
                    self.terminal_outcome == "PAUSED_SAFETY_STOP" or
                    (
                        self.mode_status_state == int(self.NavigationModeStatus.PAUSED) and
                        self.mode_status_reason == int(self.NavigationModeStatus.SAFETY_STOP)
                    )
                )
                if not (self.mode_failure_observed or safety_pause_observed):
                    failures.append(
                        "fail-closed scenario observed neither ModeCompleted failure "
                        "nor terminal safety pause"
                    )
                if self.trajectory_failure_count <= 0 and int(self.safety_kind_counts.get("2", 0)) <= 0:
                    failures.append("fail-closed scenario observed no planner failure or safety stop")
            elif expected_count <= 0:
                failures.append("mission_waypoint_count is not configured")
            elif summary["outcome"] == "COMPLETE" and self.goal_indices != expected_indices:
                initial_skip_allowed = bool(
                    self.config.get("allow_initial_pass_through_skip", False))
                valid_prefix_skip = (
                    initial_skip_allowed and expected_indices and
                    self.goal_indices == expected_indices[1:])
                if not valid_prefix_skip:
                    failures.append(
                        f"mission waypoint order mismatch: expected {expected_indices}, got {self.goal_indices}"
                    )
                else:
                    summary["skipped_initial_waypoints"] = [expected_indices[0]]
                    self._record("event", {
                        "name": "initial_pass_through_waypoint_skipped",
                        "waypoint_index": expected_indices[0],
                    })
            pillar_waypoint_index = int(self.config.get("pillar_waypoint_index", 1))
            if (summary["outcome"] == "COMPLETE" and pillar_waypoint_index >= 0 and
                    bool(self.config.get("planned_clearance_check", True))):
                detour_distances = [
                    float(item["pillar_min_distance_m"])
                    for item in self.trajectory_records
                    if int(item.get("waypoint_index", -1)) == pillar_waypoint_index and
                    item.get("pillar_min_distance_m") is not None
                ]
                if not detour_distances:
                    failures.append("no trajectory recorded for obstacle-detour waypoint")
                elif min(detour_distances) <= float(self.config.get("pillar_clearance_m", 0.8)):
                    failures.append("planned detour trajectory entered obstacle clearance")
            if self.actual_min_clearance_m is not None and self.actual_min_clearance_m <= 0.05:
                failures.append("ground-truth vehicle clearance reached collision margin")
            minimum_clearance = self.minimum_collision_clearance_m
            clearance_limit = float(self.config.get("minimum_collision_clearance_m", 0.0))
            if (
                minimum_clearance is not None
                and math.isfinite(clearance_limit)
                and clearance_limit > 0.0
                and minimum_clearance < clearance_limit
            ):
                failures.append(
                    "ground-truth vehicle clearance fell below configured safety margin"
                )
            if self.collision_count > 0:
                failures.append("ground-truth vehicle collision envelope was breached")
            if bool(self.config.get("require_map_observability", False)):
                if self.raw_lidar_roi_scan_count < 5 or self.raw_lidar_roi_max_points < 20:
                    failures.append("MAP_OBSERVABILITY_NOT_PROVEN: raw LiDAR wall ROI")
                if self.occupied_roi_max_points < 5:
                    failures.append("MAP_OBSERVABILITY_NOT_PROVEN: occupied voxel wall ROI")
            expected_velocity = self.config.get("expected_max_velocity_mps")
            setpoint_max = max(self.setpoint_speed_samples, default=0.0)
            if expected_velocity is not None and (
                not math.isfinite(float(expected_velocity)) or
                setpoint_max > float(expected_velocity) + 0.10
            ):
                failures.append("PX4 velocity setpoint exceeded mission velocity limit")
            if not self.takeoff_observed:
                failures.append("vehicle did not reach stable takeoff altitude")
            if summary["outcome"] not in {"COMPLETE", "ABORTED_OPERATOR", "PAUSED_SAFETY_STOP"}:
                failures.append(f"unexpected terminal outcome: {summary['outcome']}")
        self.output.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        self.stream.close()


def run(output: Path, config_path: Path) -> int:
    import rclpy
    import yaml

    config = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    rclpy.init(args=[])
    scenario = ExternalModeScenario(output, config)

    def stop(_signum: int, _frame: Any) -> None:
        # Interactive runs intentionally wait after handover. Preserve that
        # terminal outcome when the user ends the GUI session with Ctrl-C.
        if not scenario.handover_waiting:
            scenario.failure = "scenario interrupted"
        scenario.finish(scenario.terminal_outcome or "INTERRUPTED")

    signal.signal(signal.SIGINT, stop)
    signal.signal(signal.SIGTERM, stop)
    try:
        while rclpy.ok() and not scenario.finished:
            rclpy.spin_once(scenario.node, timeout_sec=0.1)
    finally:
        if not scenario.finished:
            scenario.finish("INTERRUPTED")
        scenario.node.destroy_node()
        rclpy.shutdown()
    summary = json.loads(output.read_text(encoding="utf-8"))
    outcome = str(summary.get("outcome", "FAILED"))
    if outcome == "COMPLETE" and not summary.get("failures"):
        return 0
    if outcome in {"ABORTED_OPERATOR", "PAUSED_SAFETY_STOP"}:
        return 2
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--config", type=Path, required=True)
    args = parser.parse_args()
    return run(args.output.resolve(), args.config.resolve())


if __name__ == "__main__":
    raise SystemExit(main())
