super_navigation_node:
  ros__parameters:
    super_navigation:
      cloud_topic: /lio/registered_points
      odometry_topic: /lio/odometry_propagated
      goal_topic: /navigation/goal
      trajectory_topic: /navigation/super_trajectory
      planning_frame: lio_odom
      planner_rate_hz: 10.0
      heartbeat_rate_hz: 50.0
      heartbeat_horizon_s: 3.0
