#!/usr/bin/env python3
"""Generate the C++ and Python SafetyProfile loaders from the YAML source."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "config/safety_profile/sitl_current_as_is.yaml"
HEADER = ROOT / "src/contracts/nav_safety_profile/include/nav_safety_profile/generated/profile.hpp"
PYTHON = ROOT / "tools/safety_profile/profile.py"


def entries(document: dict[str, Any], *, include_overlays: bool = False) -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {}

    def visit(node: Any, prefix: str) -> None:
        if not isinstance(node, dict):
            return
        if "value" in node:
            result[prefix] = node
            return
        for key, value in node.items():
            visit(value, f"{prefix}.{key}" if prefix else str(key))

    for section, value in document.items():
        if section not in {"schema_version", "profile", "overlays"}:
            visit(value, section)
    if include_overlays:
        for deployment, value in document.get("overlays", {}).items():
            visit(value, f"overlays.{deployment}")
    return result


def python_source(required: list[str]) -> str:
    required_repr = repr(tuple(required))
    return f'''# Generated by tools/safety_profile/gen.py; do not edit.
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import math
from pathlib import Path
from typing import Any

import yaml

REQUIRED_PATHS = {required_repr}


@dataclass(frozen=True)
class Profile:
    values: dict[str, Any]
    metadata: dict[str, dict[str, Any]]
    sha256: str
    hash64: str


def _canonical(value: Any) -> str:
    if isinstance(value, dict):
        return "{{" + ",".join(
            _canonical(str(key)) + ":" + _canonical(value[key])
            for key in sorted(value, key=lambda item: str(item))
        ) + "}}"
    if isinstance(value, list):
        return "[" + ",".join(_canonical(item) for item in value) + "]"
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            raise ValueError("profile contains a non-finite number")
        return format(value, ".17g")
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    raise ValueError(f"unsupported profile value type: {{type(value).__name__}}")


def _walk(document: dict[str, Any]) -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {{}}

    def visit(node: Any, prefix: str) -> None:
        if not isinstance(node, dict):
            return
        if "value" in node:
            result[prefix] = node
            return
        for key, value in node.items():
            visit(value, f"{{prefix}}.{{key}}" if prefix else str(key))

    for section, value in document.items():
        if section not in {{"schema_version", "profile", "overlays"}}:
            visit(value, section)
    return result


def _derive(path: str, record: dict[str, Any], values: dict[str, Any]) -> Any:
    if record.get("value") != "DERIVED":
        return record["value"]
    formula = record.get("derived_from", {{}}).get("formula")
    if path == "geometry.planning_radius_sum_m":
        keys = ("geometry.vehicle_radius_m", "geometry.tracking_error_budget_m",
                "geometry.localization_error_budget_m", "geometry.mapping_error_budget_m",
                "geometry.planning_margin_m")
        return sum(float(values[key]) for key in keys)
    if path == "timing.minimum_main_reserve_s" and formula == (
        "solve_deadline_s + stitch_duration_s + planner_period_s + commit_guard_s"
    ):
        return sum(float(values[f"timing.{{key}}"]) for key in (
            "solve_deadline_s", "stitch_duration_s", "planner_period_s", "commit_guard_s"))
    raise ValueError(f"unknown derived SafetyProfile field: {{path}}")


def _validate_entry(path: str, record: dict[str, Any]) -> None:
    required = {{"value", "unit", "qualification_status", "owners", "overlay",
                "sources", "superseded_sources"}}
    missing = required - record.keys()
    if missing:
        raise ValueError(f"{{path}} missing metadata: {{sorted(missing)}}")
    if record["qualification_status"] not in {{"PROVISIONAL", "ACTIVE", "NOT_EVALUABLE"}}:
        raise ValueError(f"{{path}} has invalid qualification_status")
    if record["overlay"] not in {{"allowed", "forbidden"}}:
        raise ValueError(f"{{path}} has invalid overlay policy")
    if not isinstance(record["owners"], list) or not isinstance(record["sources"], list):
        raise ValueError(f"{{path}} owners and sources must be lists")
    value = record["value"]
    if isinstance(value, bool):
        return
    if isinstance(value, (int, float)):
        if not math.isfinite(float(value)) or value < 0:
            raise ValueError(f"{{path}} is outside its valid nonnegative domain")
    elif isinstance(value, list):
        if any(not isinstance(item, (int, float)) or not math.isfinite(float(item))
               for item in value):
            raise ValueError(f"{{path}} list has invalid numeric values")


def load_profile(path: str | Path) -> Profile:
    document = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    if not isinstance(document, dict) or not isinstance(document.get("profile"), dict):
        raise ValueError("profile document must contain profile metadata")
    records = _walk(document)
    for required in REQUIRED_PATHS:
        if required not in records:
            raise ValueError(f"missing required SafetyProfile key: {{required}}")
    values: dict[str, Any] = {{}}
    metadata: dict[str, dict[str, Any]] = {{}}
    for key in REQUIRED_PATHS:
        record = records[key]
        _validate_entry(key, record)
        metadata[key] = {{field: value for field, value in record.items()
                         if field not in {{"value", "oracle_name"}}}}
        if record["value"] != "DERIVED":
            values[key] = record["value"]
    for key in REQUIRED_PATHS:
        if records[key]["value"] == "DERIVED":
            values[key] = _derive(key, records[key], values)
        if isinstance(values[key], (int, float)) and not isinstance(values[key], bool):
            if not math.isfinite(float(values[key])) or values[key] < 0:
                raise ValueError(f"{{key}} is outside its valid domain")
    for deployment, overlay in document.get("overlays", {{}}).items():
        for key, record in _walk({{deployment: overlay}}).items():
            base_key = record.get("oracle_name", key)
            base = next((item for item in records.values()
                         if item.get("oracle_name") == base_key), None)
            if base is None or base.get("overlay") != "allowed" or record.get("overlay") != "allowed":
                raise ValueError(f"{{base_key}} does not permit deployment overlays")
            _validate_entry(key, record)
    canonical = _canonical(document).encode("utf-8")
    digest = hashlib.sha256(canonical).hexdigest()
    return Profile(values, metadata, digest, digest[:16])
'''


def generate() -> dict[Path, str]:
    document = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    all_records = entries(document)
    keys = sorted(all_records, key=lambda key: all_records[key].get("value") == "DERIVED")
    # C++ output is generated from the same source; the implementation header
    # keeps a typed variant for every schema scalar and validates required paths.
    header = cxx_header(document, keys)
    return {HEADER: header, PYTHON: python_source(keys)}


def cxx_header(document: dict[str, Any], keys: list[str]) -> str:
    # The C++ generator is intentionally emitted as a separate template to make
    # the generated interface deterministic and reviewable.
    return cxx_template(document, keys)


def cxx_template(document: dict[str, Any], keys: list[str]) -> str:
    def scalar_kind(record: dict[str, Any]) -> str:
        value = record["value"]
        if value == "DERIVED":
            return "double"
        if isinstance(value, bool):
            return "bool"
        if isinstance(value, int):
            return "int64_t"
        if isinstance(value, float):
            return "double"
        if isinstance(value, list):
            return "std::vector<double>"
        return "std::string"

    def member_name(path: str) -> str:
        name = path.replace(".", "_")
        return name[:-2] + "_ns" if name.endswith("_s") else name

    records = entries(document)
    oracle_to_base = {
        record.get("oracle_name", path.split(".")[-1]): path
        for path, record in records.items()
    }
    fields = []
    parsers = []
    assignments = []
    overlay_checks = []
    for path in keys:
        kind = scalar_kind(records[path])
        field_type = "std::int64_t" if path.endswith("_s") and kind == "double" else kind
        fields.append(f"  {field_type} {member_name(path)}{{}};")
        parsers.append(f'''    {{
      const auto node = lookup(root, "{path}");
      if (!node || !node["value"]) return failure("missing required SafetyProfile key: {path}");
      Scalar value;
      const auto raw_value = node["value"];
      if (raw_value.IsScalar() && raw_value.Scalar() == "DERIVED") {{
        if (std::string("{path}") == "geometry.planning_radius_sum_m") {{
          value = number(profile.entries, "geometry.vehicle_radius_m") +
                  number(profile.entries, "geometry.tracking_error_budget_m") +
                  number(profile.entries, "geometry.localization_error_budget_m") +
                  number(profile.entries, "geometry.mapping_error_budget_m") +
                  number(profile.entries, "geometry.planning_margin_m");
        }} else if (std::string("{path}") == "timing.minimum_main_reserve_s") {{
          value = number(profile.entries, "timing.solve_deadline_s") +
                  number(profile.entries, "timing.stitch_duration_s") +
                  number(profile.entries, "timing.planner_period_s") +
                  number(profile.entries, "timing.commit_guard_s");
        }} else {{ return failure("unsupported DERIVED formula: {path}"); }}
      }} else {{
        try {{ value = node["value"].as<{kind}>(); }}
        catch (const std::exception&) {{ return failure("invalid typed value: {path}"); }}
      }}
      const auto unit = node["unit"];
      const auto status = node["qualification_status"];
      const auto owners = node["owners"];
      const auto overlay = node["overlay"];
      const auto sources = node["sources"];
      const auto superseded = node["superseded_sources"];
      if (!unit || unit.as<std::string>().empty() || !status || !owners || !overlay || !sources || !superseded)
        return failure("incomplete SafetyProfile metadata: {path}");
      const auto q = status.as<std::string>();
      if (q != "PROVISIONAL" && q != "ACTIVE" && q != "NOT_EVALUABLE")
        return failure("invalid qualification status: {path}");
      const auto overlay_text = overlay.as<std::string>();
      if (overlay_text != "allowed" && overlay_text != "forbidden")
        return failure("invalid overlay policy: {path}");
      if (!valid(value)) return failure("value outside valid domain: {path}");
      profile.entries.emplace("{path}", Entry{{value, unit.as<std::string>(), q,
        owners.as<std::vector<std::string>>(), overlay_text == "allowed",
        sources.as<std::vector<std::string>>(), superseded.as<std::vector<std::string>>()}});
    }}''')
        if field_type == "std::int64_t" and path.endswith("_s") and kind == "double":
            assignments.append(f'''    {{
      const double seconds = number(profile.entries, "{path}");
      const long double ns = static_cast<long double>(seconds) * 1000000000.0L;
      if (ns > static_cast<long double>(std::numeric_limits<std::int64_t>::max()))
        return failure("duration overflow: {path}");
      profile.typed.{member_name(path)} = static_cast<std::int64_t>(std::llround(ns));
    }}''')
        else:
            assignments.append(f'    profile.typed.{member_name(path)} = std::get<{kind}>(profile.entries.at("{path}").value);')

    for deployment, overlay_records in document.get("overlays", {}).items():
        for key, record in overlay_records.items():
            base_path = oracle_to_base.get(record.get("oracle_name", key))
            if base_path is None:
                raise ValueError(f"overlay {deployment}.{key} has no base profile key")
            overlay_checks.append(f'''    {{
      const auto overlay = lookup(root, "overlays.{deployment}.{key}");
      if (!overlay || !overlay["value"] ||
          !profile.entries.at("{base_path}").overlay_allowed ||
          !overlay["overlay"] || overlay["overlay"].as<std::string>() != "allowed")
        return failure("unauthorized or incomplete overlay: {deployment}.{key}");
      try {{
        const auto value = overlay["value"].as<double>();
        if (!std::isfinite(value) || value < 0.0) return failure("invalid overlay value: {deployment}.{key}");
      }} catch (const std::exception&) {{ return failure("invalid overlay value: {deployment}.{key}"); }}
    }}''')

    # Parse ordinary fields before derived fields so all formula inputs exist.
    return f'''// Generated by tools/safety_profile/gen.py; do not edit.
#pragma once

#include <algorithm>
#include <charconv>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <iomanip>
#include <limits>
#include <map>
#include <optional>
#include <sstream>
#include <string>
#include <type_traits>
#include <variant>
#include <vector>
#include <utility>

#include <openssl/evp.h>
#include <yaml-cpp/yaml.h>

namespace nav_safety_profile {{
using Scalar = std::variant<double, std::int64_t, bool, std::string, std::vector<double>>;
struct Entry {{
  Scalar value;
  std::string unit;
  std::string qualification_status;
  std::vector<std::string> owners;
  bool overlay_allowed{{false}};
  std::vector<std::string> sources;
  std::vector<std::string> superseded_sources;
}};
struct ProfileValues {{
{chr(10).join(fields)}
}};
struct Profile {{
  ProfileValues typed;
  std::map<std::string, Entry> entries;
  std::string sha256;
  std::uint64_t hash64{{0}};
}};
template <typename T> struct Result {{
  bool ok{{false}};
  std::optional<T> value;
  std::string error;
  explicit operator bool() const noexcept {{ return ok; }}
}};

inline std::string quote_json(const std::string& value) {{
  std::ostringstream out; out << '\"';
  for (unsigned char c : value) {{
    if (c == '\\"' || c == '\\\\') out << '\\\\' << static_cast<char>(c);
    else if (c == '\\n') out << "\\\\n";
    else if (c == '\\r') out << "\\\\r";
    else if (c == '\\t') out << "\\\\t";
    else if (c < 0x20) {{ out << "\\\\u" << std::hex << std::setw(4) << std::setfill('0') << static_cast<int>(c) << std::dec; }}
    else out << static_cast<char>(c);
  }}
  out << '\"'; return out.str();
}}
inline std::string canonical(const YAML::Node& node) {{
  if (!node || node.IsNull()) return "null";
  if (node.IsMap()) {{
    std::map<std::string, YAML::Node> ordered;
    for (const auto& item : node) ordered.emplace(item.first.as<std::string>(), item.second);
    std::string out = "{{"; bool first = true;
    for (const auto& [key, value] : ordered) {{ if (!first) out += ","; first = false; out += quote_json(key) + ":" + canonical(value); }}
    return out + "}}";
  }}
  if (node.IsSequence()) {{
    std::string out = "["; bool first = true;
    for (const auto& item : node) {{ if (!first) out += ","; first = false; out += canonical(item); }}
    return out + "]";
  }}
  const std::string value = node.Scalar();
  if (value == "true" || value == "false") return value;
  char* end = nullptr; const double number_value = std::strtod(value.c_str(), &end);
  if (end != value.c_str() && *end == '\\0' && std::isfinite(number_value)) {{
    if (value.find_first_of(".eE") == std::string::npos) {{
      try {{ return std::to_string(std::stoll(value)); }} catch (const std::exception&) {{}}
    }}
    char buffer[64];
    const auto converted = std::to_chars(buffer, buffer + sizeof(buffer), number_value, std::chars_format::general, 17);
    if (converted.ec == std::errc{{}}) return std::string(buffer, converted.ptr);
  }}
  return quote_json(value);
}}
inline bool valid(const Scalar& value) {{
  return std::visit([](const auto& item) {{
    using T = std::decay_t<decltype(item)>;
    if constexpr (std::is_same_v<T, double>) return std::isfinite(item) && item >= 0.0;
    else if constexpr (std::is_same_v<T, std::int64_t>) return item >= 0;
    else if constexpr (std::is_same_v<T, std::vector<double>>) return std::all_of(item.begin(), item.end(), [](double n) {{ return std::isfinite(n) && n >= 0.0; }});
    else return true;
  }}, value);
}}
inline double number(const std::map<std::string, Entry>& entries, const std::string& key) {{
  return std::get<double>(entries.at(key).value);
}}
inline YAML::Node lookup(const YAML::Node& root, const std::string& path) {{
  YAML::Node node = root; std::size_t begin = 0;
  while (begin < path.size()) {{ const auto end = path.find('.', begin); const auto part = path.substr(begin, end - begin); const YAML::Node next = node[part]; node.reset(next); if (end == std::string::npos) break; begin = end + 1; }}
  return node;
}}
inline Result<Profile> failure(const std::string& error) {{ return {{false, std::nullopt, error}}; }}
inline Result<Profile> load(const std::string& path) {{
  try {{
    const YAML::Node root = YAML::LoadFile(path);
    Profile profile;
{chr(10).join(parsers)}
{chr(10).join(overlay_checks)}
{chr(10).join(assignments)}
    const auto canonical_document = canonical(root);
    unsigned char digest[EVP_MAX_MD_SIZE]{{}}; unsigned int digest_size = 0;
    if (EVP_Digest(canonical_document.data(), canonical_document.size(), digest, &digest_size, EVP_sha256(), nullptr) != 1 || digest_size != 32)
      return failure("SHA-256 calculation failed");
    std::ostringstream hex; hex << std::hex << std::setfill('0');
    for (unsigned int i = 0; i < digest_size; ++i) hex << std::setw(2) << static_cast<unsigned int>(digest[i]);
    profile.sha256 = hex.str(); profile.hash64 = std::stoull(profile.sha256.substr(0, 16), nullptr, 16);
    return {{true, std::move(profile), {{}}}};
  }} catch (const std::exception& error) {{ return failure(error.what()); }}
}}
}}  // namespace nav_safety_profile
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = generate()
    changed: list[str] = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                changed.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if changed:
        print("generated SafetyProfile files are stale: " + ", ".join(changed), file=sys.stderr)
        return 1
    if not args.check:
        print(f"generated {len(outputs)} SafetyProfile outputs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
